---
- name: Install and configure Jenkins on Amazon Linux 2
  hosts: amazon_linux
  become: true
  tasks:
    - name: Update all packages
      yum:
        name: "*"
        state: latest

    - name: Enable Amazon Corretto 11
      command: amazon-linux-extras enable corretto11
      register: corretto_enable
      failed_when: "'not supported' in corretto_enable.stderr"

    - name: Install Amazon Corretto 17 (Java 17)
      yum:
        name: java-17-amazon-corretto
        state: present

    - name: Add Jenkins repository
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: Import Jenkins GPG key
      rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

    - name: Install Jenkins
      yum:
        name: jenkins
        state: present

    - name: Source /etc/environment
      shell: source /etc/environment
      args:
        executable: /bin/bash

    - name: Start and enable Jenkins service
      systemd:
        name: jenkins
        state: started
        enabled: true

    # ----------------------------------------
    # 🔹 Shared Directory Setup for ec2-user and jenkins
    # ----------------------------------------

    - name: Create a shared group
      group:
        name: shared_group
        state: present

    - name: Add ec2-user to shared_group
      user:
        name: ec2-user
        groups: shared_group
        append: yes

    - name: Add jenkins to shared_group
      user:
        name: jenkins
        groups: shared_group
        append: yes

    - name: Create a shared directory
      file:
        path: /opt/shared_directory
        state: directory
        owner: jenkins
        group: shared_group
        mode: "2775"

    - name: Set GID bit to ensure new files inherit group ownership
      file:
        path: /opt/shared_directory
        mode: "2775"
