
module "SARARG" {
  source                                   = "../_SARARG_snowflakeAccountRoleAccountRoleGrants"
  snowflakeAccountName                     = var.snowflakeAccountName
  snowflakeAuthenticator                   = var.snowflakeAuthenticator
  snowflakeClientIp                        = var.snowflakeClientIp
  snowflakeClientRequestMfaToken           = var.snowflakeClientRequestMfaToken
  snowflakeClientStoreTemporaryCredential  = var.snowflakeClientStoreTemporaryCredential
  snowflakeClientTimeout                   = var.snowflakeClientTimeout
  snowflakeDisableConsoleLogin             = var.snowflakeDisableConsoleLogin
  snowflakeDisableQueryContextCache        = var.snowflakeDisableQueryContextCache
  snowflakeDisableTelemetry                = var.snowflakeDisableTelemetry
  snowflakeDriverTracing                   = var.snowflakeDriverTracing
  snowflakeExternalBrowserTimeout          = var.snowflakeExternalBrowserTimeout
  snowflakeHost                            = var.snowflakeHost
  snowflakeIncludeRetryReason              = var.snowflakeIncludeRetryReason
  snowflakeInsecureMode                    = var.snowflakeInsecureMode
  snowflakeJwtClientTimeout                = var.snowflakeJwtClientTimeout
  snowflakeJwtExpireTimeout                = var.snowflakeJwtExpireTimeout
  snowflakeKeepSessionAlive                = var.snowflakeKeepSessionAlive
  snowflakeLoginTimeout                    = var.snowflakeLoginTimeout
  snowflakeMaxRetryCount                   = var.snowflakeMaxRetryCount
  snowflakeOcspFailOpen                    = var.snowflakeOcspFailOpen
  snowflakeOktaUrl                         = var.snowflakeOktaUrl
  snowflakeOrganizationName                = var.snowflakeOrganizationName
  snowflakeParams                          = var.snowflakeParams
  snowflakePasscode                        = var.snowflakePasscode
  snowflakePasscodeInPassword              = var.snowflakePasscodeInPassword
  snowflakePassword                        = var.snowflakePassword
  snowflakePort                            = var.snowflakePort
  snowflakePreviewFeaturesEnabled          = var.snowflakePreviewFeaturesEnabled
  snowflakePrivateKey                      = var.snowflakePrivateKey
  snowflakePrivateKeyPassphrase            = var.snowflakePrivateKeyPassphrase
  snowflakeProfile                         = var.snowflakeProfile
  snowflakeProtocol                        = var.snowflakeProtocol
  snowflakeRequestTimeout                  = var.snowflakeRequestTimeout
  snowflakeRole                            = var.snowflakeRole
  snowflakeTmpDirectoryPath                = var.snowflakeTmpDirectoryPath
  snowflakeToken                           = var.snowflakeToken
  snowflakeUser                            = var.snowflakeUser
  snowflakeValidateDefaultParameters       = var.snowflakeValidateDefaultParameters
  snowflakeWarehouse                       = var.snowflakeWarehouse
  resourceName                             = var.resourceName
  SARARG_AccountRoleComment                = var.SS_SARARG_AccountRoleComment
  SARARG_GrantPrivilegesObjects            = var.SS_SARARG_GrantPrivilegesObjects
  SARARG_GrantPrivilegesAllPrivileges      = var.SS_SARARG_GrantPrivilegesAllPrivileges
  SARARG_GrantPrivilegesAlwaysApply        = var.SS_SARARG_GrantPrivilegesAlwaysApply
  SARARG_GrantPrivilegesAlwaysApplyTrigger = var.SS_SARARG_GrantPrivilegesAlwaysApplyTrigger
  SARARG_GrantPrivilegesOnAccount          = var.SS_SARARG_GrantPrivilegesOnAccount
}

#---

module "SUP" {
  source                                                    = "../_SUP_snowflakeUserPks"
  SUP_PKS_PasswordLength                                    = var.SS_SUP_PKS_PasswordLength
  SUP_PKS_PasswordKeepers                                   = var.SS_SUP_PKS_PasswordKeepers
  SUP_PKS_PasswordLower                                     = var.SS_SUP_PKS_PasswordLower
  SUP_PKS_PasswordMinLower                                  = var.SS_SUP_PKS_PasswordMinLower
  SUP_PKS_PasswordMinNumeric                                = var.SS_SUP_PKS_PasswordMinNumeric
  SUP_PKS_PasswordMinSpecial                                = var.SS_SUP_PKS_PasswordMinSpecial
  SUP_PKS_PasswordMinUpper                                  = var.SS_SUP_PKS_PasswordMinUpper
  SUP_PKS_PasswordNumeric                                   = var.SS_SUP_PKS_PasswordNumeric
  SUP_PKS_PasswordOverrideSpecial                           = var.SS_SUP_PKS_PasswordOverrideSpecial
  SUP_PKS_PasswordSpecial                                   = var.SS_SUP_PKS_PasswordSpecial
  SUP_PKS_PasswordUpper                                     = var.SS_SUP_PKS_PasswordUpper
  tlsProxy                                                  = var.tlsProxy
  SUP_PKS_PrivateKeyAlgorithm                               = var.SS_SUP_PKS_PrivateKeyAlgorithm
  SUP_PKS_PrivateKeyEcdsaCurve                              = var.SS_SUP_PKS_PrivateKeyEcdsaCurve
  SUP_PKS_PrivateKeyRsaBits                                 = var.SS_SUP_PKS_PrivateKeyRsaBits
  awsRegion                                                 = var.awsRegion
  SUP_PKS_SWV_SecretDescription                             = var.SS_SUP_PKS_SWV_SecretDescription
  SUP_PKS_SWV_SecretKmsKeyId                                = var.SS_SUP_PKS_SWV_SecretKmsKeyId
  SUP_PKS_SWV_SecretNamePrefix                              = var.SS_SUP_PKS_SWV_SecretNamePrefix
  resourceName                                              = var.resourceName
  SUP_PKS_SWV_SecretPolicy                                  = var.SS_SUP_PKS_SWV_SecretPolicy
  SUP_PKS_SWV_SecretRecoveryWindowInDays                    = var.SS_SUP_PKS_SWV_SecretRecoveryWindowInDays
  SUP_PKS_SWV_SecretReplica                                 = var.SS_SUP_PKS_SWV_SecretReplica
  SUP_PKS_SWV_SecretForceSecretOverwrite                    = var.SS_SUP_PKS_SWV_SecretForceSecretOverwrite
  projectName                                               = var.projectName
  createdBy                                                 = var.createdBy
  deployedDate                                              = var.deployedDate
  tfModule                                                  = var.tfModule
  additionalTags                                            = var.additionalTags
  SUP_PKS_SWV_PrivateKeyP8FilePath                          = var.SS_SUP_PKS_SWV_PrivateKeyP8FilePath
  SUP_PKS_SWV_SecretVersionSecretString                     = var.SS_SUP_PKS_SWV_SecretVersionSecretString
  SUP_PKS_SWV_SecretVersionSecretBinary                     = var.SS_SUP_PKS_SWV_SecretVersionSecretBinary
  SUP_PKS_SWV_SecretVersionStages                           = var.SS_SUP_PKS_SWV_SecretVersionStages
  snowflakeAccountName                                      = var.snowflakeAccountName
  snowflakeAuthenticator                                    = var.snowflakeAuthenticator
  snowflakeClientIp                                         = var.snowflakeClientIp
  snowflakeClientRequestMfaToken                            = var.snowflakeClientRequestMfaToken
  snowflakeClientStoreTemporaryCredential                   = var.snowflakeClientStoreTemporaryCredential
  snowflakeClientTimeout                                    = var.snowflakeClientTimeout
  snowflakeDisableConsoleLogin                              = var.snowflakeDisableConsoleLogin
  snowflakeDisableQueryContextCache                         = var.snowflakeDisableQueryContextCache
  snowflakeDisableTelemetry                                 = var.snowflakeDisableTelemetry
  snowflakeDriverTracing                                    = var.snowflakeDriverTracing
  snowflakeExternalBrowserTimeout                           = var.snowflakeExternalBrowserTimeout
  snowflakeHost                                             = var.snowflakeHost
  snowflakeIncludeRetryReason                               = var.snowflakeIncludeRetryReason
  snowflakeInsecureMode                                     = var.snowflakeInsecureMode
  snowflakeJwtClientTimeout                                 = var.snowflakeJwtClientTimeout
  snowflakeJwtExpireTimeout                                 = var.snowflakeJwtExpireTimeout
  snowflakeKeepSessionAlive                                 = var.snowflakeKeepSessionAlive
  snowflakeLoginTimeout                                     = var.snowflakeLoginTimeout
  snowflakeMaxRetryCount                                    = var.snowflakeMaxRetryCount
  snowflakeOcspFailOpen                                     = var.snowflakeOcspFailOpen
  snowflakeOktaUrl                                          = var.snowflakeOktaUrl
  snowflakeOrganizationName                                 = var.snowflakeOrganizationName
  snowflakeParams                                           = var.snowflakeParams
  snowflakePasscode                                         = var.snowflakePasscode
  snowflakePasscodeInPassword                               = var.snowflakePasscodeInPassword
  snowflakePassword                                         = var.snowflakePassword
  snowflakePort                                             = var.snowflakePort
  snowflakePreviewFeaturesEnabled                           = var.snowflakePreviewFeaturesEnabled
  snowflakePrivateKey                                       = var.snowflakePrivateKey
  snowflakePrivateKeyPassphrase                             = var.snowflakePrivateKeyPassphrase
  snowflakeProfile                                          = var.snowflakeProfile
  snowflakeProtocol                                         = var.snowflakeProtocol
  snowflakeRequestTimeout                                   = var.snowflakeRequestTimeout
  snowflakeRole                                             = var.snowflakeRole
  snowflakeTmpDirectoryPath                                 = var.snowflakeTmpDirectoryPath
  snowflakeToken                                            = var.snowflakeToken
  snowflakeUser                                             = var.snowflakeUser
  snowflakeValidateDefaultParameters                        = var.snowflakeValidateDefaultParameters
  snowflakeWarehouse                                        = var.snowflakeWarehouse
  SUP_SnowflakeUserAbortDetachedQuery                       = var.SS_SUP_SnowflakeUserAbortDetachedQuery
  SUP_SnowflakeUserAutocommit                               = var.SS_SUP_SnowflakeUserAutocommit
  SUP_SnowflakeUserBinaryInputFormat                        = var.SS_SUP_SnowflakeUserBinaryInputFormat
  SUP_SnowflakeUserBinaryOutputFormat                       = var.SS_SUP_SnowflakeUserBinaryOutputFormat
  SUP_SnowflakeUserClientMemoryLimit                        = var.SS_SUP_SnowflakeUserClientMemoryLimit
  SUP_SnowflakeUserClientMetadataRequestUseConnectionCtx    = var.SS_SUP_SnowflakeUserClientMetadataRequestUseConnectionCtx
  SUP_SnowflakeUserClientPrefetchThreads                    = var.SS_SUP_SnowflakeUserClientPrefetchThreads
  SUP_SnowflakeUserClientResultChunkSize                    = var.SS_SUP_SnowflakeUserClientResultChunkSize
  SUP_SnowflakeUserClientResultColumnCaseInsensitive        = var.SS_SUP_SnowflakeUserClientResultColumnCaseInsensitive
  SUP_SnowflakeUserClientSessionKeepAlive                   = var.SS_SUP_SnowflakeUserClientSessionKeepAlive
  SUP_SnowflakeUserClientSessionKeepAliveHeartbeatFrequency = var.SS_SUP_SnowflakeUserClientSessionKeepAliveHeartbeatFrequency
  SUP_SnowflakeUserClientTimestampTypeMapping               = var.SS_SUP_SnowflakeUserClientTimestampTypeMapping
  SUP_SnowflakeUserComment                                  = var.SS_SUP_SnowflakeUserComment
  SUP_SnowflakeUserDateInputFormat                          = var.SS_SUP_SnowflakeUserDateInputFormat
  SUP_SnowflakeUserDateOutputFormat                         = var.SS_SUP_SnowflakeUserDateOutputFormat
  SUP_SnowflakeUserDaysToExpiry                             = var.SS_SUP_SnowflakeUserDaysToExpiry
  SUP_SnowflakeUserDefaultNamespace                         = var.SS_SUP_SnowflakeUserDefaultNamespace
  SUP_SnowflakeUserDefaultRole                              = var.SS_SUP_SnowflakeUserDefaultRole
  SUP_SnowflakeUserDefaultSecondaryRolesOption              = var.SS_SUP_SnowflakeUserDefaultSecondaryRolesOption
  SUP_SnowflakeUserDefaultWarehouse                         = var.SS_SUP_SnowflakeUserDefaultWarehouse
  SUP_SnowflakeUserDisableMfa                               = var.SS_SUP_SnowflakeUserDisableMfa
  SUP_SnowflakeUserDisabled                                 = var.SS_SUP_SnowflakeUserDisabled
  SUP_SnowflakeUserDisplayName                              = var.SS_SUP_SnowflakeUserDisplayName
  SUP_SnowflakeUserEmail                                    = var.SS_SUP_SnowflakeUserEmail
  SUP_SnowflakeUserEnableUnloadPhysicalTypeOptimization     = var.SS_SUP_SnowflakeUserEnableUnloadPhysicalTypeOptimization
  SUP_SnowflakeUserEnableUnredactedQuerySyntaxError         = var.SS_SUP_SnowflakeUserEnableUnredactedQuerySyntaxError
  SUP_SnowflakeUserErrorOnNondeterministicMerge             = var.SS_SUP_SnowflakeUserErrorOnNondeterministicMerge
  SUP_SnowflakeUserErrorOnNondeterministicUpdate            = var.SS_SUP_SnowflakeUserErrorOnNondeterministicUpdate
  SUP_SnowflakeUserFirstName                                = var.SS_SUP_SnowflakeUserFirstName
  SUP_SnowflakeUserGeographyOutputFormat                    = var.SS_SUP_SnowflakeUserGeographyOutputFormat
  SUP_SnowflakeUserGeometryOutputFormat                     = var.SS_SUP_SnowflakeUserGeometryOutputFormat
  SUP_SnowflakeUserJdbcTreatDecimalAsInt                    = var.SS_SUP_SnowflakeUserJdbcTreatDecimalAsInt
  SUP_SnowflakeUserJdbcTreatTimestampNtzAsUtc               = var.SS_SUP_SnowflakeUserJdbcTreatTimestampNtzAsUtc
  SUP_SnowflakeUserJdbcUseSessionTimezone                   = var.SS_SUP_SnowflakeUserJdbcUseSessionTimezone
  SUP_SnowflakeUserJsonIndent                               = var.SS_SUP_SnowflakeUserJsonIndent
  SUP_SnowflakeUserLastName                                 = var.SS_SUP_SnowflakeUserLastName
  SUP_SnowflakeUserLockTimeout                              = var.SS_SUP_SnowflakeUserLockTimeout
  SUP_SnowflakeUserLogLevel                                 = var.SS_SUP_SnowflakeUserLogLevel
  SUP_SnowflakeUserLoginName                                = var.SS_SUP_SnowflakeUserLoginName
  SUP_SnowflakeUserMiddleName                               = var.SS_SUP_SnowflakeUserMiddleName
  SUP_SnowflakeUserMinsToBypassMfa                          = var.SS_SUP_SnowflakeUserMinsToBypassMfa
  SUP_SnowflakeUserMinsToUnlock                             = var.SS_SUP_SnowflakeUserMinsToUnlock
  SUP_SnowflakeUserMultiStatementCount                      = var.SS_SUP_SnowflakeUserMultiStatementCount
  SUP_SnowflakeUserMustChangePassword                       = var.SS_SUP_SnowflakeUserMustChangePassword
  SUP_SnowflakeUserNetworkPolicy                            = var.SS_SUP_SnowflakeUserNetworkPolicy
  SUP_SnowflakeUserNoorderSequenceAsDefault                 = var.SS_SUP_SnowflakeUserNoorderSequenceAsDefault
  SUP_SnowflakeUserOdbcTreatDecimalAsInt                    = var.SS_SUP_SnowflakeUserOdbcTreatDecimalAsInt
  SUP_SnowflakeUserPassword                                 = var.SS_SUP_SnowflakeUserPassword
  SUP_SnowflakeUserPreventUnloadToInternalStages            = var.SS_SUP_SnowflakeUserPreventUnloadToInternalStages
  SUP_SnowflakeUserQueryTag                                 = var.SS_SUP_SnowflakeUserQueryTag
  SUP_SnowflakeUserQuotedIdentifiersIgnoreCase              = var.SS_SUP_SnowflakeUserQuotedIdentifiersIgnoreCase
  SUP_SnowflakeUserRowsPerRuleset                           = var.SS_SUP_SnowflakeUserRowsPerRuleset
  SUP_SnowflakeUserRsaPublicKey2                            = var.SS_SUP_SnowflakeUserRsaPublicKey2
  SUP_SnowflakeUserS3StageVpceDnsName                       = var.SS_SUP_SnowflakeUserS3StageVpceDnsName
  SUP_SnowflakeUserSearchPath                               = var.SS_SUP_SnowflakeUserSearchPath
  SUP_SnowflakeUserSimulatedDataSharingConsumer             = var.SS_SUP_SnowflakeUserSimulatedDataSharingConsumer
  SUP_SnowflakeUserStatementQueuedTimeoutInSeconds          = var.SS_SUP_SnowflakeUserStatementQueuedTimeoutInSeconds
  SUP_SnowflakeUserStatementTimeoutInSeconds                = var.SS_SUP_SnowflakeUserStatementTimeoutInSeconds
  SUP_SnowflakeUserStrictJsonOutput                         = var.SS_SUP_SnowflakeUserStrictJsonOutput
  SUP_SnowflakeUserTimeInputFormat                          = var.SS_SUP_SnowflakeUserTimeInputFormat
  SUP_SnowflakeUserTimeOutputFormat                         = var.SS_SUP_SnowflakeUserTimeOutputFormat
  SUP_SnowflakeUserTimestampDayIsAlways24h                  = var.SS_SUP_SnowflakeUserTimestampDayIsAlways24h
  SUP_SnowflakeUserTimestampInputFormat                     = var.SS_SUP_SnowflakeUserTimestampInputFormat
  SUP_SnowflakeUserTimestampLtzOutputFormat                 = var.SS_SUP_SnowflakeUserTimestampLtzOutputFormat
  SUP_SnowflakeUserTimestampNtzOutputFormat                 = var.SS_SUP_SnowflakeUserTimestampNtzOutputFormat
  SUP_SnowflakeUserTimestampOutputFormat                    = var.SS_SUP_SnowflakeUserTimestampOutputFormat
  SUP_SnowflakeUserTimestampTypeMapping                     = var.SS_SUP_SnowflakeUserTimestampTypeMapping
  SUP_SnowflakeUserTimestampTzOutputFormat                  = var.SS_SUP_SnowflakeUserTimestampTzOutputFormat
  SUP_SnowflakeUserTimezone                                 = var.SS_SUP_SnowflakeUserTimezone
  SUP_SnowflakeUserTraceLevel                               = var.SS_SUP_SnowflakeUserTraceLevel
  SUP_SnowflakeUserTransactionAbortOnError                  = var.SS_SUP_SnowflakeUserTransactionAbortOnError
  SUP_SnowflakeUserTransactionDefaultIsolationLevel         = var.SS_SUP_SnowflakeUserTransactionDefaultIsolationLevel
  SUP_SnowflakeUserTwoDigitCenturyStart                     = var.SS_SUP_SnowflakeUserTwoDigitCenturyStart
  SUP_SnowflakeUserUnsupportedDdlAction                     = var.SS_SUP_SnowflakeUserUnsupportedDdlAction
  SUP_SnowflakeUserUsedCachedResult                         = var.SS_SUP_SnowflakeUserUsedCachedResult
  SUP_SnowflakeUserWeekOfYearPolicy                         = var.SS_SUP_SnowflakeUserWeekOfYearPolicy
  SUP_SnowflakeUserWeekStart                                = var.SS_SUP_SnowflakeUserWeekStart
}

#---

module "grantAccountRole" {
  source                                  = "../../snowflake/principals/genericGrantAccountRole"
  snowflakeAccountName                    = var.snowflakeAccountName
  snowflakeAuthenticator                  = var.snowflakeAuthenticator
  snowflakeClientIp                       = var.snowflakeClientIp
  snowflakeClientRequestMfaToken          = var.snowflakeClientRequestMfaToken
  snowflakeClientStoreTemporaryCredential = var.snowflakeClientStoreTemporaryCredential
  snowflakeClientTimeout                  = var.snowflakeClientTimeout
  snowflakeDisableConsoleLogin            = var.snowflakeDisableConsoleLogin
  snowflakeDisableQueryContextCache       = var.snowflakeDisableQueryContextCache
  snowflakeDisableTelemetry               = var.snowflakeDisableTelemetry
  snowflakeDriverTracing                  = var.snowflakeDriverTracing
  snowflakeExternalBrowserTimeout         = var.snowflakeExternalBrowserTimeout
  snowflakeHost                           = var.snowflakeHost
  snowflakeIncludeRetryReason             = var.snowflakeIncludeRetryReason
  snowflakeInsecureMode                   = var.snowflakeInsecureMode
  snowflakeJwtClientTimeout               = var.snowflakeJwtClientTimeout
  snowflakeJwtExpireTimeout               = var.snowflakeJwtExpireTimeout
  snowflakeKeepSessionAlive               = var.snowflakeKeepSessionAlive
  snowflakeLoginTimeout                   = var.snowflakeLoginTimeout
  snowflakeMaxRetryCount                  = var.snowflakeMaxRetryCount
  snowflakeOcspFailOpen                   = var.snowflakeOcspFailOpen
  snowflakeOktaUrl                        = var.snowflakeOktaUrl
  snowflakeOrganizationName               = var.snowflakeOrganizationName
  snowflakeParams                         = var.snowflakeParams
  snowflakePasscode                       = var.snowflakePasscode
  snowflakePasscodeInPassword             = var.snowflakePasscodeInPassword
  snowflakePassword                       = var.snowflakePassword
  snowflakePort                           = var.snowflakePort
  snowflakePreviewFeaturesEnabled         = var.snowflakePreviewFeaturesEnabled
  snowflakePrivateKey                     = var.snowflakePrivateKey
  snowflakePrivateKeyPassphrase           = var.snowflakePrivateKeyPassphrase
  snowflakeProfile                        = var.snowflakeProfile
  snowflakeProtocol                       = var.snowflakeProtocol
  snowflakeRequestTimeout                 = var.snowflakeRequestTimeout
  snowflakeRole                           = var.snowflakeRole
  snowflakeTmpDirectoryPath               = var.snowflakeTmpDirectoryPath
  snowflakeToken                          = var.snowflakeToken
  snowflakeUser                           = var.snowflakeUser
  snowflakeValidateDefaultParameters      = var.snowflakeValidateDefaultParameters
  snowflakeWarehouse                      = var.snowflakeWarehouse
  grantAccountRoleName                    = var.SS_GrantAccountRoleName
  grantAccountRoleParentRoleName          = var.SS_GrantAccountRoleParentRoleName
  grantAccountRoleUserName                = var.SS_GrantAccountRoleUserName
}

#---


# module "SARARG" {
#   source                                  = "../_SARARG_snowflakeAccountRoleAccountRoleGrants"
#   snowflakeAccountName                    = var.snowflakeAccountName
#   snowflakeAuthenticator                  = var.snowflakeAuthenticator
#   snowflakeClientIp                       = var.snowflakeClientIp
#   snowflakeClientRequestMfaToken          = var.snowflakeClientRequestMfaToken
#   snowflakeClientStoreTemporaryCredential = var.snowflakeClientStoreTemporaryCredential
#   snowflakeClientTimeout                  = var.snowflakeClientTimeout
#   snowflakeDisableConsoleLogin            = var.snowflakeDisableConsoleLogin
#   snowflakeDisableQueryContextCache       = var.snowflakeDisableQueryContextCache
#   snowflakeDisableTelemetry               = var.snowflakeDisableTelemetry
#   snowflakeDriverTracing                  = var.snowflakeDriverTracing
#   snowflakeExternalBrowserTimeout         = var.snowflakeExternalBrowserTimeout
#   snowflakeHost                           = var.snowflakeHost
#   snowflakeIncludeRetryReason             = var.snowflakeIncludeRetryReason
#   snowflakeInsecureMode                   = var.snowflakeInsecureMode
#   snowflakeJwtClientTimeout               = var.snowflakeJwtClientTimeout
#   snowflakeJwtExpireTimeout               = var.snowflakeJwtExpireTimeout
#   snowflakeKeepSessionAlive               = var.snowflakeKeepSessionAlive
#   snowflakeLoginTimeout                   = var.snowflakeLoginTimeout
#   snowflakeMaxRetryCount                  = var.snowflakeMaxRetryCount
#   snowflakeOcspFailOpen                   = var.snowflakeOcspFailOpen
#   snowflakeOktaUrl                        = var.snowflakeOktaUrl
#   snowflakeOrganizationName               = var.snowflakeOrganizationName
#   snowflakeParams                         = var.snowflakeParams
#   snowflakePasscode                       = var.snowflakePasscode
#   snowflakePasscodeInPassword             = var.snowflakePasscodeInPassword
#   snowflakePassword                       = var.snowflakePassword
#   snowflakePort                           = var.snowflakePort
#   snowflakePreveiwFeaturesEnabled         = var.snowflakePreveiwFeaturesEnabled
#   snowflakePrivateKey                     = var.snowflakePrivateKey
#   snowflakePrivateKeyPassphrase           = var.snowflakePrivateKeyPassphrase
#   snowflakeProfile                        = var.snowflakeProfile
#   snowflakeProtocol                       = var.snowflakeProtocol
#   snowflakeRequestTimeout                 = var.snowflakeRequestTimeout
#   snowflakeRole                           = var.snowflakeRole
#   snowflakeTmpDirectoryPath               = var.snowflakeTmpDirectoryPath
#   snowflakeToken                          = var.snowflakeToken
#   # snowflakeTokenAccessor = var.snowflakeTokenAccessor
#   snowflakeUser                            = var.snowflakeUser
#   snowflakeValidateDefaultParameters       = var.snowflakeValidateDefaultParameters
#   snowflakeWarehouse                       = var.snowflakeWarehouse
#   resourceName                             = var.resourceName
#   SARARG_AccountRoleComment                = var.SS_SARARG_AccountRoleComment
#   SARARG_GrantPrivilegesObjects            = var.SS_SARARG_GrantPrivilegesObjects
#   SARARG_GrantPrivilegesAllPrivileges      = var.SS_SARARG_GrantPrivilegesAllPrivileges
#   SARARG_GrantPrivilegesAlwaysApply        = var.SS_SARARG_GrantPrivilegesAlwaysApply
#   SARARG_GrantPrivilegesAlwaysApplyTrigger = var.SS_SARARG_GrantPrivilegesAlwaysApplyTrigger
#   SARARG_GrantPrivilegesOnAccount          = var.SS_SARARG_GrantPrivilegesOnAccount
# }

# #---

# module "SUP" {
#   source                                  = "../_SUP_snowflakeUserPks"
#   SUP_PKS_PasswordLength                  = var.SS_SUP_PKS_PasswordLength
#   SUP_PKS_PasswordKeepers                 = var.SS_SUP_PKS_PasswordKeepers
#   SUP_PKS_PasswordLower                   = var.SS_SUP_PKS_PasswordLower
#   SUP_PKS_PasswordMinLower                = var.SS_SUP_PKS_PasswordMinLower
#   SUP_PKS_PasswordMinNumeric              = var.SS_SUP_PKS_PasswordMinNumeric
#   SUP_PKS_PasswordMinSpecial              = var.SS_SUP_PKS_PasswordMinSpecial
#   SUP_PKS_PasswordMinUpper                = var.SS_SUP_PKS_PasswordMinUpper
#   SUP_PKS_PasswordNumeric                 = var.SS_SUP_PKS_PasswordNumeric
#   SUP_PKS_PasswordOverrideSpecial         = var.SS_SUP_PKS_PasswordOverrideSpecial
#   SUP_PKS_PasswordSpecial                 = var.SS_SUP_PKS_PasswordSpecial
#   SUP_PKS_PasswordUpper                   = var.SS_SUP_PKS_PasswordUpper
#   tlsProxy                                = var.tlsProxy
#   SUP_PKS_PrivateKeyAlgorithm             = var.SS_SUP_PKS_PrivateKeyAlgorithm
#   SUP_PKS_PrivateKeyEcdsaCurve            = var.SS_SUP_PKS_PrivateKeyEcdsaCurve
#   SUP_PKS_PrivateKeyRsaBits               = var.SS_SUP_PKS_PrivateKeyRsaBits
#   awsRegion                               = var.awsRegion
#   SUP_PKS_SWV_SecretKmsKeyId              = var.SS_SUP_PKS_SWV_SecretKmsKeyId
#   resourceName                            = var.resourceName
#   SUP_PKS_SWV_SecretPolicy                = var.SS_SUP_PKS_SWV_SecretPolicy
#   SUP_PKS_SWV_SecretRecoveryWindowInDays  = var.SS_SUP_PKS_SWV_SecretRecoveryWindowInDays
#   SUP_PKS_SWV_SecretReplica               = var.SS_SUP_PKS_SWV_SecretReplica
#   SUP_PKS_SWV_SecretForceSecretOverwrite  = var.SS_SUP_PKS_SWV_SecretForceSecretOverwrite
#   projectName                             = var.projectName
#   creator                                 = var.creator
#   deployedDate                            = var.deployedDate
#   tfModule                                = var.tfModule
#   additionalTags                          = var.additionalTags
#   SUP_PKS_privateKeyP8FilePath            = var.SS_SUP_PKS_privateKeyP8FilePath
#   SUP_PKS_SWV_SecretVersionSecretString   = var.SS_SUP_PKS_SWV_SecretVersionSecretString
#   SUP_PKS_SWV_SecretVersionSecretBinary   = var.SS_SUP_PKS_SWV_SecretVersionSecretBinary
#   SUP_PKS_SWV_SecretVersionStages         = var.SS_SUP_PKS_SWV_SecretVersionStages
#   snowflakeAccountName                    = var.snowflakeAccountName
#   snowflakeAuthenticator                  = var.snowflakeAuthenticator
#   snowflakeClientIp                       = var.snowflakeClientIp
#   snowflakeClientRequestMfaToken          = var.snowflakeClientRequestMfaToken
#   snowflakeClientStoreTemporaryCredential = var.snowflakeClientStoreTemporaryCredential
#   snowflakeClientTimeout                  = var.snowflakeClientTimeout
#   snowflakeDisableConsoleLogin            = var.snowflakeDisableConsoleLogin
#   snowflakeDisableQueryContextCache       = var.snowflakeDisableQueryContextCache
#   snowflakeDisableTelemetry               = var.snowflakeDisableTelemetry
#   snowflakeDriverTracing                  = var.snowflakeDriverTracing
#   snowflakeExternalBrowserTimeout         = var.snowflakeExternalBrowserTimeout
#   snowflakeHost                           = var.snowflakeHost
#   snowflakeIncludeRetryReason             = var.snowflakeIncludeRetryReason
#   snowflakeInsecureMode                   = var.snowflakeInsecureMode
#   snowflakeJwtClientTimeout               = var.snowflakeJwtClientTimeout
#   snowflakeJwtExpireTimeout               = var.snowflakeJwtExpireTimeout
#   snowflakeKeepSessionAlive               = var.snowflakeKeepSessionAlive
#   snowflakeLoginTimeout                   = var.snowflakeLoginTimeout
#   snowflakeMaxRetryCount                  = var.snowflakeMaxRetryCount
#   snowflakeOcspFailOpen                   = var.snowflakeOcspFailOpen
#   snowflakeOktaUrl                        = var.snowflakeOktaUrl
#   snowflakeOrganizationName               = var.snowflakeOrganizationName
#   snowflakeParams                         = var.snowflakeParams
#   snowflakePasscode                       = var.snowflakePasscode
#   snowflakePasscodeInPassword             = var.snowflakePasscodeInPassword
#   snowflakePassword                       = var.snowflakePassword
#   snowflakePort                           = var.snowflakePort
#   snowflakePreveiwFeaturesEnabled         = var.snowflakePreveiwFeaturesEnabled
#   snowflakePrivateKey                     = var.snowflakePrivateKey
#   snowflakePrivateKeyPassphrase           = var.snowflakePrivateKeyPassphrase
#   snowflakeProfile                        = var.snowflakeProfile
#   snowflakeProtocol                       = var.snowflakeProtocol
#   snowflakeRequestTimeout                 = var.snowflakeRequestTimeout
#   snowflakeRole                           = var.snowflakeRole
#   snowflakeTmpDirectoryPath               = var.snowflakeTmpDirectoryPath
#   snowflakeToken                          = var.snowflakeToken
#   # snowflakeTokenAccessor = var.snowflakeTokenAccessor
#   snowflakeUser                                             = var.snowflakeUser
#   snowflakeValidateDefaultParameters                        = var.snowflakeValidateDefaultParameters
#   snowflakeWarehouse                                        = var.snowflakeWarehouse
#   SUP_SnowflakeUserAbortDetachedQuery                       = var.SS_SUP_SnowflakeUserAbortDetachedQuery
#   SUP_SnowflakeUserAutocommit                               = var.SS_SUP_SnowflakeUserAutocommit
#   SUP_SnowflakeUserBinaryInputFormat                        = var.SS_SUP_SnowflakeUserBinaryInputFormat
#   SUP_SnowflakeUserBinaryOutputFormat                       = var.SS_SUP_SnowflakeUserBinaryOutputFormat
#   SUP_SnowflakeUserClientMemoryLimit                        = var.SS_SUP_SnowflakeUserClientMemoryLimit
#   SUP_SnowflakeUserClientMetadataRequestUseConnectionCtx    = var.SS_SUP_SnowflakeUserClientMetadataRequestUseConnectionCtx
#   SUP_SnowflakeUserClientPrefetchThreads                    = var.SS_SUP_SnowflakeUserClientPrefetchThreads
#   SUP_SnowflakeUserClientResultChunkSize                    = var.SS_SUP_SnowflakeUserClientResultChunkSize
#   SUP_SnowflakeUserClientResultColumnCaseInsensitive        = var.SS_SUP_SnowflakeUserClientResultColumnCaseInsensitive
#   SUP_SnowflakeUserClientSessionKeepAlive                   = var.SS_SUP_SnowflakeUserClientSessionKeepAlive
#   SUP_SnowflakeUserClientSessionKeepAliveHeartbeatFrequency = var.SS_SUP_SnowflakeUserClientSessionKeepAliveHeartbeatFrequency
#   SUP_SnowflakeUserClientTimestampTypeMapping               = var.SS_SUP_SnowflakeUserClientTimestampTypeMapping
#   SUP_SnowflakeUserComment                                  = var.SS_SUP_SnowflakeUserComment
#   SUP_SnowflakeUserDateInputFormat                          = var.SS_SUP_SnowflakeUserDateInputFormat
#   SUP_SnowflakeUserDateOutputFormat                         = var.SS_SUP_SnowflakeUserDateOutputFormat
#   SUP_SnowflakeUserDaysToExpiry                             = var.SS_SUP_SnowflakeUserDaysToExpiry
#   SUP_SnowflakeUserDefaultNamespace                         = var.SS_SUP_SnowflakeUserDefaultNamespace
#   SUP_SnowflakeUserDefaultRole                              = module.SARARG.SARARG_AccountRoleFullyQualifiedName
#   SUP_SnowflakeUserDefaultSecondaryRolesOption              = var.SS_SUP_SnowflakeUserDefaultSecondaryRolesOption
#   SUP_SnowflakeUserDefaultWarehouse                         = var.SS_SUP_SnowflakeUserDefaultWarehouse
#   SUP_SnowflakeUserDisableMfa                               = var.SS_SUP_SnowflakeUserDisableMfa
#   SUP_SnowflakeUserDisabled                                 = var.SS_SUP_SnowflakeUserDisabled
#   SUP_SnowflakeUserDisplayName                              = var.SS_SUP_SnowflakeUserDisplayName
#   SUP_SnowflakeUserEmail                                    = var.SS_SUP_SnowflakeUserEmail
#   SUP_SnowflakeUserEnableUnloadPhysicalTypeOptimization     = var.SS_SUP_SnowflakeUserEnableUnloadPhysicalTypeOptimization
#   SUP_SnowflakeUserEnableUnredactedQuerySyntaxError         = var.SS_SUP_SnowflakeUserEnableUnredactedQuerySyntaxError
#   SUP_SnowflakeUserErrorOnNondeterministicMerge             = var.SS_SUP_SnowflakeUserErrorOnNondeterministicMerge
#   SUP_SnowflakeUserErrorOnNondeterministicUpdate            = var.SS_SUP_SnowflakeUserErrorOnNondeterministicUpdate
#   SUP_SnowflakeUserFirstName                                = var.SS_SUP_SnowflakeUserFirstName
#   SUP_SnowflakeUserGeographyOutputFormat                    = var.SS_SUP_SnowflakeUserGeographyOutputFormat
#   SUP_SnowflakeUserGeometryOutputFormat                     = var.SS_SUP_SnowflakeUserGeometryOutputFormat
#   SUP_SnowflakeUserJdbcTreatDecimalAsInt                    = var.SS_SUP_SnowflakeUserJdbcTreatDecimalAsInt
#   SUP_SnowflakeUserJdbcTreatTimestampNtzAsUtc               = var.SS_SUP_SnowflakeUserJdbcTreatTimestampNtzAsUtc
#   SUP_SnowflakeUserJdbcUseSessionTimezone                   = var.SS_SUP_SnowflakeUserJdbcUseSessionTimezone
#   SUP_SnowflakeUserJsonIndent                               = var.SS_SUP_SnowflakeUserJsonIndent
#   SUP_SnowflakeUserLastName                                 = var.SS_SUP_SnowflakeUserLastName
#   SUP_SnowflakeUserLockTimeout                              = var.SS_SUP_SnowflakeUserLockTimeout
#   SUP_SnowflakeUserLogLevel                                 = var.SS_SUP_SnowflakeUserLogLevel
#   SUP_SnowflakeUserLoginName                                = var.SS_SUP_SnowflakeUserLoginName
#   SUP_SnowflakeUserMiddleName                               = var.SS_SUP_SnowflakeUserMiddleName
#   SUP_SnowflakeUserMinsToBypassMfa                          = var.SS_SUP_SnowflakeUserMinsToBypassMfa
#   SUP_SnowflakeUserMinsToUnlock                             = var.SS_SUP_SnowflakeUserMinsToUnlock
#   SUP_SnowflakeUserMultiStatementCount                      = var.SS_SUP_SnowflakeUserMultiStatementCount
#   SUP_SnowflakeUserMustChangePassword                       = var.SS_SUP_SnowflakeUserMustChangePassword
#   SUP_SnowflakeUserNetworkPolicy                            = var.SS_SUP_SnowflakeUserNetworkPolicy
#   SUP_SnowflakeUserNoorderSequenceAsDefault                 = var.SS_SUP_SnowflakeUserNoorderSequenceAsDefault
#   SUP_SnowflakeUserOdbcTreatDecimalAsInt                    = var.SS_SUP_SnowflakeUserOdbcTreatDecimalAsInt
#   SUP_SnowflakeUserPassword                                 = var.SS_SUP_SnowflakeUserPassword
#   SUP_SnowflakeUserPreventUnloadToInternalStages            = var.SS_SUP_SnowflakeUserPreventUnloadToInternalStages
#   SUP_SnowflakeUserQueryTag                                 = var.SS_SUP_SnowflakeUserQueryTag
#   SUP_SnowflakeUserQuotedIdentifiersIgnoreCase              = var.SS_SUP_SnowflakeUserQuotedIdentifiersIgnoreCase
#   SUP_SnowflakeUserRowsPerRuleset                           = var.SS_SUP_SnowflakeUserRowsPerRuleset
#   SUP_SnowflakeUserRsaPublicKey2                            = var.SS_SUP_SnowflakeUserRsaPublicKey2
#   SUP_SnowflakeUserS3StageVpceDnsName                       = var.SS_SUP_SnowflakeUserS3StageVpceDnsName
#   SUP_SnowflakeUserSearchPath                               = var.SS_SUP_SnowflakeUserSearchPath
#   SUP_SnowflakeUserSimulatedDataSharingConsumer             = var.SS_SUP_SnowflakeUserSimulatedDataSharingConsumer
#   SUP_SnowflakeUserStatementQueuedTimeoutInSeconds          = var.SS_SUP_SnowflakeUserStatementQueuedTimeoutInSeconds
#   SUP_SnowflakeUserStatementTimeoutInSeconds                = var.SS_SUP_SnowflakeUserStatementTimeoutInSeconds
#   SUP_SnowflakeUserStrictJsonOutput                         = var.SS_SUP_SnowflakeUserStrictJsonOutput
#   SUP_SnowflakeUserTimeInputFormat                          = var.SS_SUP_SnowflakeUserTimeInputFormat
#   SUP_SnowflakeUserTimeOutputFormat                         = var.SS_SUP_SnowflakeUserTimeOutputFormat
#   SUP_SnowflakeUserTimestampDayIsAlways24h                  = var.SS_SUP_SnowflakeUserTimestampDayIsAlways24h
#   SUP_SnowflakeUserTimestampInputFormat                     = var.SS_SUP_SnowflakeUserTimestampInputFormat
#   SUP_SnowflakeUserTimestampLtzOutputFormat                 = var.SS_SUP_SnowflakeUserTimestampLtzOutputFormat
#   SUP_SnowflakeUserTimestampNtzOutputFormat                 = var.SS_SUP_SnowflakeUserTimestampNtzOutputFormat
#   SUP_SnowflakeUserTimestampOutputFormat                    = var.SS_SUP_SnowflakeUserTimestampOutputFormat
#   SUP_SnowflakeUserTimestampTypeMapping                     = var.SS_SUP_SnowflakeUserTimestampTypeMapping
#   SUP_SnowflakeUserTimestampTzOutputFormat                  = var.SS_SUP_SnowflakeUserTimestampTzOutputFormat
#   SUP_SnowflakeUserTimezone                                 = var.SS_SUP_SnowflakeUserTimezone
#   SUP_SnowflakeUserTraceLevel                               = var.SS_SUP_SnowflakeUserTraceLevel
#   SUP_SnowflakeUserTransactionAbortOnError                  = var.SS_SUP_SnowflakeUserTransactionAbortOnError
#   SUP_SnowflakeUserTransactionDefaultIsolationLevel         = var.SS_SUP_SnowflakeUserTransactionDefaultIsolationLevel
#   SUP_SnowflakeUserTwoDigitCenturyStart                     = var.SS_SUP_SnowflakeUserTwoDigitCenturyStart
#   SUP_SnowflakeUserUnsupportedDdlAction                     = var.SS_SUP_SnowflakeUserUnsupportedDdlAction
#   SUP_SnowflakeUserUsedCachedResult                         = var.SS_SUP_SnowflakeUserUsedCachedResult
#   SUP_SnowflakeUserWeekOfYearPolicy                         = var.SS_SUP_SnowflakeUserWeekOfYearPolicy
#   SUP_SnowflakeUserWeekStart                                = var.SS_SUP_SnowflakeUserWeekStart
# }

# #---

# module "grantAccountRole" {
#   source                                  = "../../snowflake/principals/genericGrantAccountRole"
#   snowflakeAccountName                    = var.snowflakeAccountName
#   snowflakeAuthenticator                  = var.snowflakeAuthenticator
#   snowflakeClientIp                       = var.snowflakeClientIp
#   snowflakeClientRequestMfaToken          = var.snowflakeClientRequestMfaToken
#   snowflakeClientStoreTemporaryCredential = var.snowflakeClientStoreTemporaryCredential
#   snowflakeClientTimeout                  = var.snowflakeClientTimeout
#   snowflakeDisableConsoleLogin            = var.snowflakeDisableConsoleLogin
#   snowflakeDisableQueryContextCache       = var.snowflakeDisableQueryContextCache
#   snowflakeDisableTelemetry               = var.snowflakeDisableTelemetry
#   snowflakeDriverTracing                  = var.snowflakeDriverTracing
#   snowflakeExternalBrowserTimeout         = var.snowflakeExternalBrowserTimeout
#   snowflakeHost                           = var.snowflakeHost
#   snowflakeIncludeRetryReason             = var.snowflakeIncludeRetryReason
#   snowflakeInsecureMode                   = var.snowflakeInsecureMode
#   snowflakeJwtClientTimeout               = var.snowflakeJwtClientTimeout
#   snowflakeJwtExpireTimeout               = var.snowflakeJwtExpireTimeout
#   snowflakeKeepSessionAlive               = var.snowflakeKeepSessionAlive
#   snowflakeLoginTimeout                   = var.snowflakeLoginTimeout
#   snowflakeMaxRetryCount                  = var.snowflakeMaxRetryCount
#   snowflakeOcspFailOpen                   = var.snowflakeOcspFailOpen
#   snowflakeOktaUrl                        = var.snowflakeOktaUrl
#   snowflakeOrganizationName               = var.snowflakeOrganizationName
#   snowflakeParams                         = var.snowflakeParams
#   snowflakePasscode                       = var.snowflakePasscode
#   snowflakePasscodeInPassword             = var.snowflakePasscodeInPassword
#   snowflakePassword                       = var.snowflakePassword
#   snowflakePort                           = var.snowflakePort
#   snowflakePreveiwFeaturesEnabled         = var.snowflakePreveiwFeaturesEnabled
#   snowflakePrivateKey                     = var.snowflakePrivateKey
#   snowflakePrivateKeyPassphrase           = var.snowflakePrivateKeyPassphrase
#   snowflakeProfile                        = var.snowflakeProfile
#   snowflakeProtocol                       = var.snowflakeProtocol
#   snowflakeRequestTimeout                 = var.snowflakeRequestTimeout
#   snowflakeRole                           = var.snowflakeRole
#   snowflakeTmpDirectoryPath               = var.snowflakeTmpDirectoryPath
#   snowflakeToken                          = var.snowflakeToken
#   # snowflakeTokenAccessor = var.snowflakeTokenAccessor
#   snowflakeUser                      = var.snowflakeUser
#   snowflakeValidateDefaultParameters = var.snowflakeValidateDefaultParameters
#   snowflakeWarehouse                 = var.snowflakeWarehouse
#   grantAccountRoleName               = module.SARARG.SARARG_AccountRoleFullyQualifiedName
#   grantAccountRoleParentRoleName     = var.SS_GrantAccountRoleParentRoleName
#   grantAccountRoleUserName           = module.SUP.SUP_SnowflakeUserFullyQualifiedName
# }