provider "google" {
  project = var.projectId
  region  = var.gcpRegion
}



    module "NWEIPN" {
  source = "../../gcp/cloudComputeNetwork/_NWEIPN_networkWithExternalIpNat"
gcpProjectId = var.gcpProjectId
gcpRegion = var.gcpRegion
resourceName = var.resourceName
NWEIPN_NWSAF_NetworkDescription = var.CSCRAPFG_NWEIPN_NWSAF_NetworkDescription
NWEIPN_NWSAF_NetworkAutoCreateSubNetworks = var.CSCRAPFG_NWEIPN_NWSAF_NetworkAutoCreateSubNetworks
NWEIPN_NWSAF_NetworkRoutingMode = var.CSCRAPFG_NWEIPN_NWSAF_NetworkRoutingMode
NWEIPN_NWSAF_NetworkMaximumTransmissionUnitBytes = var.CSCRAPFG_NWEIPN_NWSAF_NetworkMaximumTransmissionUnitBytes
NWEIPN_NWSAF_NetworkEnableUlaInternalIpv6 = var.CSCRAPFG_NWEIPN_NWSAF_NetworkEnableUlaInternalIpv6
NWEIPN_NWSAF_NetworkInternalIpv6Range = var.CSCRAPFG_NWEIPN_NWSAF_NetworkInternalIpv6Range
NWEIPN_NWSAF_NetworkFirewallPolicyEnforcementOrder = var.CSCRAPFG_NWEIPN_NWSAF_NetworkFirewallPolicyEnforcementOrder
NWEIPN_NWSAF_NetworkDeleteDefaultRoutesOnCreate = var.CSCRAPFG_NWEIPN_NWSAF_NetworkDeleteDefaultRoutesOnCreate
NWEIPN_NWSAF_SubnetworkNetwork = var.CSCRAPFG_NWEIPN_NWSAF_SubnetworkNetwork
NWEIPN_NWSAF_SubnetworkDescription = var.CSCRAPFG_NWEIPN_NWSAF_SubnetworkDescription
NWEIPN_NWSAF_SubnetworkIpCidrRange = var.CSCRAPFG_NWEIPN_NWSAF_SubnetworkIpCidrRange
NWEIPN_NWSAF_SubnetworkReservedInternalRange = var.CSCRAPFG_NWEIPN_NWSAF_SubnetworkReservedInternalRange
NWEIPN_NWSAF_SubnetworkPurpose = var.CSCRAPFG_NWEIPN_NWSAF_SubnetworkPurpose
NWEIPN_NWSAF_SubnetworkRole = var.CSCRAPFG_NWEIPN_NWSAF_SubnetworkRole
NWEIPN_NWSAF_SubnetworkSecondaryIpRange = var.CSCRAPFG_NWEIPN_NWSAF_SubnetworkSecondaryIpRange
NWEIPN_NWSAF_SubnetworkPrivateIpGoogleAccess = var.CSCRAPFG_NWEIPN_NWSAF_SubnetworkPrivateIpGoogleAccess
NWEIPN_NWSAF_SubnetworkPrivateIpv6GoogleAccess = var.CSCRAPFG_NWEIPN_NWSAF_SubnetworkPrivateIpv6GoogleAccess
NWEIPN_NWSAF_SubnetworkLogConfig = var.CSCRAPFG_NWEIPN_NWSAF_SubnetworkLogConfig
NWEIPN_NWSAF_SubnetworkStackType = var.CSCRAPFG_NWEIPN_NWSAF_SubnetworkStackType
NWEIPN_NWSAF_SubnetworkIpv6AccessType = var.CSCRAPFG_NWEIPN_NWSAF_SubnetworkIpv6AccessType
NWEIPN_NWSAF_SubnetworkExternalIpv6Prefix = var.CSCRAPFG_NWEIPN_NWSAF_SubnetworkExternalIpv6Prefix
NWEIPN_NWSAF_SubnetworkSendSecondaryIpRangeIfEmpty = var.CSCRAPFG_NWEIPN_NWSAF_SubnetworkSendSecondaryIpRangeIfEmpty
NWEIPN_NWSAF_IngressFirewallNetwork = var.CSCRAPFG_NWEIPN_NWSAF_IngressFirewallNetwork
NWEIPN_NWSAF_IngressFirewallRulesAllow = var.CSCRAPFG_NWEIPN_NWSAF_IngressFirewallRulesAllow
NWEIPN_NWSAF_IngressFirewallDeny = var.CSCRAPFG_NWEIPN_NWSAF_IngressFirewallDeny
NWEIPN_NWSAF_IngressFirewallDescription = var.CSCRAPFG_NWEIPN_NWSAF_IngressFirewallDescription
NWEIPN_NWSAF_IngressFirewallDestinationRanges = var.CSCRAPFG_NWEIPN_NWSAF_IngressFirewallDestinationRanges
NWEIPN_NWSAF_IngressFirewallDirection = var.CSCRAPFG_NWEIPN_NWSAF_IngressFirewallDirection
NWEIPN_NWSAF_IngressFirewallDisabled = var.CSCRAPFG_NWEIPN_NWSAF_IngressFirewallDisabled
NWEIPN_NWSAF_IngressFirewallLogConfig = var.CSCRAPFG_NWEIPN_NWSAF_IngressFirewallLogConfig
NWEIPN_NWSAF_IngressFirewallPriority = var.CSCRAPFG_NWEIPN_NWSAF_IngressFirewallPriority
NWEIPN_NWSAF_IngressFirewallSourceRanges = var.CSCRAPFG_NWEIPN_NWSAF_IngressFirewallSourceRanges
NWEIPN_NWSAF_IngressFirewallSourceServiceAccounts = var.CSCRAPFG_NWEIPN_NWSAF_IngressFirewallSourceServiceAccounts
NWEIPN_NWSAF_IngressFirewallSourceTags = var.CSCRAPFG_NWEIPN_NWSAF_IngressFirewallSourceTags
NWEIPN_NWSAF_IngressFirewallTargetServiceAccounts = var.CSCRAPFG_NWEIPN_NWSAF_IngressFirewallTargetServiceAccounts
NWEIPN_NWSAF_IngressFirewallTargetTags = var.CSCRAPFG_NWEIPN_NWSAF_IngressFirewallTargetTags
NWEIPN_NWSAF_EgressFirewallNetwork = var.CSCRAPFG_NWEIPN_NWSAF_EgressFirewallNetwork
NWEIPN_NWSAF_EgressFirewallRulesAllow = var.CSCRAPFG_NWEIPN_NWSAF_EgressFirewallRulesAllow
NWEIPN_NWSAF_EgressFirewallDeny = var.CSCRAPFG_NWEIPN_NWSAF_EgressFirewallDeny
NWEIPN_NWSAF_EgressFirewallDescription = var.CSCRAPFG_NWEIPN_NWSAF_EgressFirewallDescription
NWEIPN_NWSAF_EgressFirewallDestinationRanges = var.CSCRAPFG_NWEIPN_NWSAF_EgressFirewallDestinationRanges
NWEIPN_NWSAF_EgressFirewallDirection = var.CSCRAPFG_NWEIPN_NWSAF_EgressFirewallDirection
NWEIPN_NWSAF_EgressFirewallDisabled = var.CSCRAPFG_NWEIPN_NWSAF_EgressFirewallDisabled
NWEIPN_NWSAF_EgressFirewallLogConfig = var.CSCRAPFG_NWEIPN_NWSAF_EgressFirewallLogConfig
NWEIPN_NWSAF_EgressFirewallPriority = var.CSCRAPFG_NWEIPN_NWSAF_EgressFirewallPriority
NWEIPN_NWSAF_EgressFirewallSourceRanges = var.CSCRAPFG_NWEIPN_NWSAF_EgressFirewallSourceRanges
NWEIPN_NWSAF_EgressFirewallSourceServiceAccounts = var.CSCRAPFG_NWEIPN_NWSAF_EgressFirewallSourceServiceAccounts
NWEIPN_NWSAF_EgressFirewallSourceTags = var.CSCRAPFG_NWEIPN_NWSAF_EgressFirewallSourceTags
NWEIPN_NWSAF_EgressFirewallTargetServiceAccounts = var.CSCRAPFG_NWEIPN_NWSAF_EgressFirewallTargetServiceAccounts
NWEIPN_NWSAF_EgressFirewallTargetTags = var.CSCRAPFG_NWEIPN_NWSAF_EgressFirewallTargetTags
deployedDate = var.deployedDate
projectName = var.projectName
createdBy = var.createdBy
tfModule = var.tfModule
additionalTags = var.additionalTags
NWEIPN_NWEA_NetworkAddressAddress = var.CSCRAPFG_NWEIPN_NWEA_NetworkAddressAddress
NWEIPN_NWEA_NetworkAddressType = var.CSCRAPFG_NWEIPN_NWEA_NetworkAddressType
NWEIPN_NWEA_NetworkAddressNetworkTier = var.CSCRAPFG_NWEIPN_NWEA_NetworkAddressNetworkTier
NWEIPN_NWEA_NetworkRouterNetwork = var.CSCRAPFG_NWEIPN_NWEA_NetworkRouterNetwork
NWEIPN_NWEA_NetworkRouterDescription = var.CSCRAPFG_NWEIPN_NWEA_NetworkRouterDescription
NWEIPN_NWEA_NetworkRouterBgp = var.CSCRAPFG_NWEIPN_NWEA_NetworkRouterBgp
NWEIPN_NWEA_NetworkRouterEncryptedInterconnectRouter = var.CSCRAPFG_NWEIPN_NWEA_NetworkRouterEncryptedInterconnectRouter
NWEIPN_NWEA_NatSourceSubnetworkIpRangesToNat = var.CSCRAPFG_NWEIPN_NWEA_NatSourceSubnetworkIpRangesToNat
NWEIPN_NWEA_NatIpAllocateOption = var.CSCRAPFG_NWEIPN_NWEA_NatIpAllocateOption
NWEIPN_NWEA_NatInitialNatIps = var.CSCRAPFG_NWEIPN_NWEA_NatInitialNatIps
NWEIPN_NWEA_NatDrainNatIps = var.CSCRAPFG_NWEIPN_NWEA_NatDrainNatIps
NWEIPN_NWEA_NatSubnetwork = var.CSCRAPFG_NWEIPN_NWEA_NatSubnetwork
NWEIPN_NWEA_NatMinPortsPerVm = var.CSCRAPFG_NWEIPN_NWEA_NatMinPortsPerVm
NWEIPN_NWEA_NatMaxPortsPerVm = var.CSCRAPFG_NWEIPN_NWEA_NatMaxPortsPerVm
NWEIPN_NWEA_NatEnableDynamicPortAllocation = var.CSCRAPFG_NWEIPN_NWEA_NatEnableDynamicPortAllocation
NWEIPN_NWEA_NatUdpIdleTimeoutSec = var.CSCRAPFG_NWEIPN_NWEA_NatUdpIdleTimeoutSec
NWEIPN_NWEA_NatIcmpIdleTimeoutSec = var.CSCRAPFG_NWEIPN_NWEA_NatIcmpIdleTimeoutSec
NWEIPN_NWEA_NatTcpEstablishedIdleTimeoutSec = var.CSCRAPFG_NWEIPN_NWEA_NatTcpEstablishedIdleTimeoutSec
NWEIPN_NWEA_NatTcpTransitoryIdleTimeoutSec = var.CSCRAPFG_NWEIPN_NWEA_NatTcpTransitoryIdleTimeoutSec
NWEIPN_NWEA_NatTcpTimeWaitTimeoutSec = var.CSCRAPFG_NWEIPN_NWEA_NatTcpTimeWaitTimeoutSec
NWEIPN_NWEA_NatLogConfig = var.CSCRAPFG_NWEIPN_NWEA_NatLogConfig
NWEIPN_NWEA_NatEndpointTypes = var.CSCRAPFG_NWEIPN_NWEA_NatEndpointTypes
NWEIPN_NWEA_NatRules = var.CSCRAPFG_NWEIPN_NWEA_NatRules
NWEIPN_NWEA_NatEnableEndpointIndependentMapping = var.CSCRAPFG_NWEIPN_NWEA_NatEnableEndpointIndependentMapping
NWEIPN_NWEA_NatAutoNetworkTier = var.CSCRAPFG_NWEIPN_NWEA_NatAutoNetworkTier
NWEIPN_VpcAccessConnectorNetwork = var.CSCRAPFG_NWEIPN_VpcAccessConnectorNetwork
NWEIPN_VpcAccessConnectorIpCidrRange = var.CSCRAPFG_NWEIPN_VpcAccessConnectorIpCidrRange
NWEIPN_VpcAccessConnectorMachineType = var.CSCRAPFG_NWEIPN_VpcAccessConnectorMachineType
NWEIPN_VpcAccessConnectorMinThroughput = var.CSCRAPFG_NWEIPN_VpcAccessConnectorMinThroughput
NWEIPN_VpcAccessConnectorMinInstances = var.CSCRAPFG_NWEIPN_VpcAccessConnectorMinInstances
NWEIPN_VpcAccessConnectorMaxInstances = var.CSCRAPFG_NWEIPN_VpcAccessConnectorMaxInstances
NWEIPN_VpcAccessConnectorMaxThroughput = var.CSCRAPFG_NWEIPN_VpcAccessConnectorMaxThroughput
NWEIPN_VpcAccessConnectorSubnet = var.CSCRAPFG_NWEIPN_VpcAccessConnectorSubnet
}

#---

module "CSDIU" {
  source = "../../gcp/googleCloudSql/_CSDIU_cloudSqlDatabaseInstanceUser"

  projectId                                             = var.projectId
  gcpRegion                                             = var.gcpRegion
  resourceName                                          = var.resourceName
  CSDIU_DatabaseInstanceDatabaseVersion                 = var.CSCRAPFG_DatabaseInstanceDatabaseVersion
  CSDIU_DatabaseInstanceRootPassword                    = var.CSCRAPFG_DatabaseInstanceRootPassword
  CSDIU_DatabaseInstanceDeletionProtection              = var.CSCRAPFG_DatabaseInstanceDeletionProtection
  CSDIU_DatabaseInstanceTier                            = var.CSCRAPFG_DatabaseInstanceTier
  CSDIU_DatabaseInstanceEdition                         = var.CSCRAPFG_DatabaseInstanceEdition
  projectName                                           = var.projectName
  deployedDate                                          = var.deployedDate
  createdBy                                             = var.createdBy
  CSDIU_DatabaseInstanceActivationPolicy                = var.CSCRAPFG_DatabaseInstanceActivationPolicy
  CSDIU_DatabaseInstanceAvailabilityType                = var.CSCRAPFG_DatabaseInstanceAvailabilityType
  CSDIU_DatabaseInstanceCollation                       = var.CSCRAPFG_DatabaseInstanceCollation
  CSDIU_DatabaseInstanceDiskAutoresize                  = var.CSCRAPFG_DatabaseInstanceDiskAutoresize
  CSDIU_DatabaseInstanceDiskAutoresizeLimit             = var.CSCRAPFG_DatabaseInstanceDiskAutoresizeLimit
  CSDIU_DatabaseInstanceDiskSize                        = var.CSCRAPFG_DatabaseInstanceDiskSize
  CSDIU_DatabaseInstanceDiskType                        = var.CSCRAPFG_DatabaseInstanceDiskType
  CSDIU_DatabaseInstanceAuthorizedNetworkIpRange        = var.CSCRAPFG_DatabaseInstanceAuthorizedNetworkIpRange
  CSDIU_DatabaseDeletionPolicy                          = var.CSCRAPFG_DatabaseDeletionPolicy
  CSDIU_DatabaseUserPassword                            = var.CSCRAPFG_DatabaseUserPassword
  CSDIU_DatabaseUserType                                = var.CSCRAPFG_DatabaseUserType
  CSDIU_DatabaseUserDeletionPolicy                      = var.CSCRAPFG_DatabaseUserDeletionPolicy
  CSDIU_DatabasePublicIpSecretVersionEnabled            = var.CSCRAPFG_DatabasePublicIpSecretVersionEnabled
  CSDIU_DatabasePublicIpSecretVersionDeletionPolicy     = var.CSCRAPFG_DatabasePublicIpSecretVersionDeletionPolicy
  CSDIU_DatabaseUserNameSecretVersionEnabled            = var.CSCRAPFG_DatabaseUserNameSecretVersionEnabled
  CSDIU_DatabaseUserNameSecretVersionDeletionPolicy     = var.CSCRAPFG_DatabaseUserNameSecretVersionDeletionPolicy
  CSDIU_DatabaseUserPasswordSecretVersionEnabled        = var.CSCRAPFG_DatabaseUserPasswordSecretVersionEnabled
  CSDIU_DatabaseUserPasswordSecretVersionDeletionPolicy = var.CSCRAPFG_DatabaseUserPasswordSecretVersionDeletionPolicy
  CSDIU_DatabaseNameSecretVersionEnabled                = var.CSCRAPFG_DatabaseNameSecretVersionEnabled
  CSDIU_DatabaseNameSecretVersionDeletionPolicy         = var.CSCRAPFG_DatabaseNameSecretVersionDeletionPolicy
}

module "CRDPFG" {
  source = "../_CRDPFG_cloudRunDeploymentPushFromGithub"

  projectId                                                       = var.projectId
  gcpRegion                                                       = var.gcpRegion
  resourceName                                                    = var.resourceName
  projectName                                                     = var.projectName
  deployedDate                                                    = var.deployedDate
  createdBy                                                       = var.createdBy
  CRDPFG_SecretVersionSecretData                                  = var.CSCRAPFG_CRDPFG_SecretVersionSecretData
  CRDPFG_SecretVersionEnabled                                     = var.CSCRAPFG_CRDPFG_SecretVersionEnabled
  CRDPFG_SecretVersionDeletionPolicy                              = var.CSCRAPFG_CRDPFG_SecretVersionDeletionPolicy
  CRDPFG_CloudBuildTriggerServiceAccountAccountId                 = "${var.resourceName}-prod"
  CRDPFG_CloudBuildTriggerServiceAccountDisabled                  = var.CSCRAPFG__CloudBuildTriggerServiceAccountDisabled
  CRDPFG_CloudBuildTriggerServiceAccountCreateIgnoreAlreadyExists = var.CSCRAPFG__CloudBuildTriggerServiceAccountCreateIgnoreAlreadyExists
  CRDPFG_CloudBuildTriggerRoleId                                  = "${var.CSCRAPFG_CloudBuildTriggerRoleId}Prod"
  CRDPFG_CloudBuildTriggerRoleStage                               = var.CSCRAPFG__CloudBuildTriggerRoleStage
  CRDPFG_CloudBuildTriggerYamlPath                                = var.CSCRAPFG__CloudBuildTriggerYamlPath
  CRDPFG_CloudBuildTriggerGithubRepoName                          = var.CSCRAPFG_CloudBuildTriggerGithubRepoName
  CRDPFG_CloudBuildTriggerBranchName                              = var.CSCRAPFG__CloudBuildTriggerBranchName
  CRDPFG_CloudBuildTriggerArtifactRepoName                        = var.CSCRAPFG_CloudBuildTriggerArtifactRepoName
  CRDPFG_CloudBuildTriggerBucketName                              = var.CSCRAPFG__CloudBuildTriggerBucketName
  CRDPFG_CloudRunConcurrentRequests                               = var.CSCRAPFG__CloudRunConcurrentRequests
  CRDPFG_CloudRunRequestsTimeout                                  = var.CSCRAPFG__CloudRunRequestsTimeout
  CRDPFG_CloudRunPortNumber                                       = var.CSCRAPFG__CloudRunPortNumber
  CRDPFG_CloudRunMinInstances                                     = var.CSCRAPFG__CloudRunMinInstances
  CRDPFG_CloudRunMaxInstances                                     = var.CSCRAPFG__CloudRunMaxInstances
  CRDPFG_CloudRunVpcConnector                                     = module.NWEIPN.NWEIPN_VpcAccessConnectorName #module.networkWithExternalIpNat.vpcAccessConnectorName
  CRDPFG_CloudRunNumberOfVcpus                                    = var.CSCRAPFG__CloudRunNumberOfVcpus
  CRDPFG_CloudRunAmountOfMemory                                   = var.CSCRAPFG__CloudRunAmountOfMemory
  CRDPFG_CloudRunEnvVariableName                                  = var.CSCRAPFG__CloudRunEnvVariableName
  CRDPFG_CloudBuildTriggerAdditionalSubstitutions                 = var.CSCRAPFG__CloudBuildTriggerAdditionalSubstitutions
  CRDPFG_CloudRunAlertPolicyNotificationChannelId                 = var.CSCRAPFG__CloudRunAlertPolicyNotificationChannelId
  CRDPFG_CloudRunAlertPolicyNotificationRateLimit                 = var.CSCRAPFG__CloudRunAlertPolicyNotificationRateLimit
  CRDPFG_CloudRunAlertPolicyAutoClose                             = var.CSCRAPFG__CloudRunAlertPolicyAutoClose
}