---
- name: Install Jenkins and Configure Jenkins Group & Directory
  hosts: all
  become: yes # Run tasks with sudo privileges

  tasks:
    # 1. Update system packages
    - name: Update and upgrade system packages
      apt:
        update_cache: yes
        upgrade: yes

    # 2. Install required dependencies
    - name: Install required dependencies
      apt:
        name:
          - openjdk-17-jdk
          - curl
          - gnupg
          - software-properties-common
        state: present

    # 3. Add Jenkins repository key
    - name: Add Jenkins repository key
      shell: |
        curl -fsSL https://pkg.jenkins.io/debian/jenkins.io-2023.key | tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null

    # 4. Add Jenkins repository
    - name: Add Jenkins repository
      shell: |
        echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian binary/" | tee /etc/apt/sources.list.d/jenkins.list > /dev/null

    # 5. Update package list again after adding Jenkins repo
    - name: Update package list
      apt:
        update_cache: yes

    # 6. Install Jenkins
    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    # 7. Start and enable Jenkins service on boot
    - name: Ensure Jenkins service is running and enabled
      systemd:
        name: jenkins
        state: started
        enabled: yes

    # 8. Create jenkins_group
    - name: Create jenkins_group (if not exists)
      group:
        name: jenkins_group
        state: present

    # 9. Add ubuntu and jenkins users to jenkins_group
    - name: Add ubuntu user to jenkins_group
      user:
        name: ubuntu
        groups: jenkins_group
        append: yes

    - name: Add jenkins user to jenkins_group
      user:
        name: jenkins
        groups: jenkins_group
        append: yes

    # 10. Create jenkins_directory
    - name: Create jenkins_directory
      file:
        path: /opt/jenkins_directory
        state: directory
        owner: jenkins
        group: jenkins_group
        mode: "2775"

    # 11. Ensure jenkins_group has full read/write permissions on jenkins_directory
    - name: Set GID bit and ensure new files inherit group permissions
      file:
        path: /opt/jenkins_directory
        state: directory
        mode: "2775"

    - name: Ensure all files and subdirectories inside jenkins_directory inherit correct permissions
      command: chmod -R 2775 /opt/jenkins_directory

    - name: Ensure all new files in jenkins_directory inherit jenkins_group ownership
      command: find /opt/jenkins_directory -type d -exec chmod g+s {} \;
