---
- name: Install GitHub CLI on Ubuntu 24.04
  hosts: remoteCode
  become: yes # Runs commands with sudo privileges

  tasks:
    - name: Update and upgrade system packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install required dependencies (curl, gnupg)
      apt:
        name:
          - curl
          - gnupg
        state: present

    - name: Ensure curl is installed
      shell: type -p curl >/dev/null || sudo apt install curl -y
      args:
        executable: /bin/bash

    - name: Add GitHub CLI GPG key
      shell: |
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | tee /usr/share/keyrings/githubcli-archive-keyring.gpg > /dev/null

    - name: Add GitHub CLI repository
      shell: |
        echo "deb [signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null

    - name: Update package list after adding new repository
      apt:
        update_cache: yes

    - name: Install GitHub CLI
      apt:
        name: gh
        state: present

    - name: Verify GitHub CLI installation
      command: gh --version
      register: gh_version_output
      changed_when: false

    - name: Display GitHub CLI version
      debug:
        msg: "{{ gh_version_output.stdout }}"
