ubuntu_server:
  hosts:
    44.212.75.153: # Replace with your instance IP
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/test.pem
      ansible_python_interpreter: /usr/bin/python3
