ubuntu_server:
  hosts:
    18.212.193.175: # Replace with your instance IP
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/test.pem
      ansible_python_interpreter: /usr/bin/python3
