ubuntu_server:
  hosts:
    107.20.217.98: # Replace with your instance IP
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/tgbfs-web-app-instance.pem
      ansible_python_interpreter: /usr/bin/python3
