apiVersion: v1
kind: Namespace
metadata:
  name: aws-observability
  labels:
    name: aws-observability
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: aws-logging
  namespace: aws-observability
data:
  output.conf: |
    [OUTPUT]
        Name cloudwatch_logs
        Match *
        region us-east-1
        log_group_name eks/bc-hipaa-prefect
        log_stream_prefix minion-
