apiVersion: v1
kind: Service
metadata:
  name: prometheus-prod-grafana
  namespace: prometheus
spec:
  selector:
    app.kubernetes.io/instance: prometheus-prod
    app.kubernetes.io/name: grafana
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
