SELECT 
    USER_NAME, 
    QUERY_TEXT, 
    START_TIME,
    EXECUTION_STATUS
FROM 
    SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE 
    QUERY_TEXT ILIKE '%create or replace dynamic table F000725.ANALYTICS_READY_TABLES%'
    AND START_TIME >= DATEADD(hour, -1, CURRENT_TIMESTAMP())
    AND EXECUTION_STATUS = 'SUCCESS'
    AND USER_NAME != 'ART_AUTOMATOR'
ORDER BY 
    START_TIME DESC